packages:
  - 'packages/*'
  - 'packages/routing-sdk/**'
  - 'apps/*'
  - 'apis/*'
  - 'examples/*'
  - 'scripts'

catalog:
  viem: ^2.21.22
  wagmi: ^2.12.17
  next: 14.2.14
  react: ^18.2.0
  react-dom: ^18.2.0
  wrangler: 3.81.0
  eslint: ^8.32.0
  '@next/eslint-plugin-next': 14.2.3
  '@aptos-labs/ts-sdk': 1.30.0
